name: to_do_list
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.3.0
  flutter_local_notifications: ^19.2.1
  # flutter_local_notifications: ^16.1.0
  # timezone: ^0.9.2
  intl: ^0.20.2
  flutter_launcher_icons: ^0.14.3
  path_provider: ^2.1.5
  uuid: ^4.5.1
  share_plus: ^11.0.0
  vibration: ^3.1.3
  google_fonts: ^6.2.1
  lottie: ^3.1.2
  timezone: ^0.10.0
  awesome_notifications: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/image/logo.png
    - assets/animations/confetti.json

flutter_icons:
  android: true
  ios: true
  image_path: "assets/image/logo.png"